// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vspi_m_top.h for the primary calling header

#ifndef VERILATED_VSPI_M_TOP_SPI_M_TOP_H_
#define VERILATED_VSPI_M_TOP_SPI_M_TOP_H_  // guard

#include "verilated.h"


class Vspi_m_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vspi_m_top_spi_m_top final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(reg_we,0,0);
        VL_IN8(reg_addr,5,0);
        VL_IN8(reg_re,0,0);
        VL_IN8(rxd,0,0);
        VL_IN8(ss_in_n,0,0);
        VL_OUT8(sclk_out,0,0);
        VL_OUT8(txd,0,0);
        VL_OUT8(ss_n,3,0);
        VL_OUT8(ssi_busy,0,0);
        VL_OUT8(ssi_txe_intr,0,0);
        VL_OUT8(ssi_txo_intr,0,0);
        VL_OUT8(ssi_rxu_intr,0,0);
        VL_OUT8(ssi_rxf_intr,0,0);
        VL_OUT8(ssi_rxo_intr,0,0);
        VL_OUT8(ssi_mst_intr,0,0);
        VL_IN8(SPEC_CFS_MIN,3,0);
        VL_IN8(SPEC_HOLD_SS,3,0);
        VL_IN8(SPEC_TXFTLR_DFLT,3,0);
        VL_OUT8(cov_fsm_state_id,3,0);
        VL_OUT8(cov_sclk_re,0,0);
        VL_OUT8(cov_sclk_fe,0,0);
        VL_OUT8(cov_sclk_out,0,0);
        VL_OUT8(cov_sclk_mask,0,0);
        VL_OUT8(cov_bit_cnt,5,0);
        VL_OUT8(cov_ctrl_cnt,3,0);
        VL_OUT8(cov_f_done,0,0);
        VL_OUT8(cov_c_done,0,0);
        VL_OUT8(cov_x_done,0,0);
        VL_OUT8(cov_last_frame,0,0);
        VL_OUT8(cov_tx_shift_en,0,0);
        VL_OUT8(cov_rx_shift_en,0,0);
        VL_OUT8(cov_load_tx_shift,0,0);
        VL_OUT8(cov_load_tx_buffer,0,0);
        VL_OUT8(cov_load_rx_buf,0,0);
        VL_OUT8(cov_s3,0,0);
        VL_OUT8(cov_txd,0,0);
        VL_OUT8(cov_ss_in_n,0,0);
        VL_OUT8(cov_ss_active,0,0);
        VL_OUT8(cov_dfs,4,0);
        VL_OUT8(cov_eff_dfs,4,0);
        VL_OUT8(cov_cfs,3,0);
        VL_OUT8(cov_eff_cfs,3,0);
        VL_OUT8(cov_baud2,0,0);
        VL_OUT8(cov_tmod,1,0);
        VL_OUT8(cov_frf,1,0);
        VL_OUT8(cov_scph,0,0);
        VL_OUT8(cov_scpol,0,0);
        VL_OUT8(cov_srl_test,0,0);
        VL_OUT8(cov_ss_tgl_en,0,0);
        VL_OUT8(cov_slv_oe,0,0);
        VL_OUT8(cov_ser,3,0);
        VL_OUT8(cov_tx_level,3,0);
        VL_OUT8(cov_rx_level,3,0);
        VL_OUT8(cov_tx_full,0,0);
        VL_OUT8(cov_tx_empty,0,0);
        VL_OUT8(cov_rx_full,0,0);
        VL_OUT8(cov_rx_empty,0,0);
        VL_OUT8(cov_tx_overflow,0,0);
        VL_OUT8(cov_rx_overflow,0,0);
        VL_OUT8(cov_rx_underflow,0,0);
        VL_OUT8(cov_risr,5,0);
        VL_OUT8(cov_isr,5,0);
    };
    struct {
        VL_OUT8(cov_imr,5,0);
        VL_OUT8(cov_ssi_txe_intr,0,0);
        VL_OUT8(cov_ssi_mst_intr,0,0);
        VL_OUT8(cov_s1,0,0);
        VL_OUT8(cov_multi_mst_sync,0,0);
        VL_OUT8(cov_s2,0,0);
        VL_OUT8(cov_hold_ss_cnt,3,0);
        VL_OUT8(cov_start_xfer,0,0);
        VL_OUT8(cov_fsm_busy,0,0);
        VL_OUT8(cov_fsm_sleep,0,0);
        VL_OUT8(cov_ssi_busy,0,0);
        VL_OUT8(cov_ssi_sleep,0,0);
        VL_OUT8(cov_rx_push,0,0);
        VL_OUT8(cov_tx_pop,0,0);
        VL_OUT8(cov_mwcr,2,0);
        VL_OUT8(cov_spi0_control,0,0);
        VL_OUT8(cov_spi1_control,0,0);
        VL_OUT8(cov_txftlr,3,0);
        VL_OUT8(cov_s0,0,0);
        CData/*0:0*/ sclk_re;
        CData/*0:0*/ sclk_fe;
        CData/*0:0*/ sclk_mask;
        CData/*0:0*/ fsm_slv_sel;
        CData/*0:0*/ ssi_oe_n;
        CData/*0:0*/ fsm_busy;
        CData/*0:0*/ fsm_sleep;
        CData/*0:0*/ fsm_multi_mst;
        CData/*0:0*/ load_tx_shift;
        CData/*0:0*/ load_tx_buffer;
        CData/*0:0*/ load_rx_buf;
        CData/*0:0*/ tx_shift_en;
        CData/*0:0*/ rx_shift_en;
        CData/*0:0*/ load_start_bit;
        CData/*0:0*/ ssp_load_tx_shift;
        CData/*4:0*/ tx_dfs;
        CData/*0:0*/ start_xfer;
        CData/*0:0*/ baud2;
        CData/*0:0*/ multi_mst_sync;
        CData/*0:0*/ mst_contention;
        CData/*0:0*/ tx_push;
        CData/*0:0*/ rx_pop;
        CData/*0:0*/ tx_pop;
        CData/*0:0*/ rx_push;
        CData/*0:0*/ tx_overflow;
        CData/*0:0*/ cov_tx_push;
        CData/*0:0*/ tx_full;
        CData/*0:0*/ tx_empty;
        CData/*0:0*/ rx_full;
        CData/*0:0*/ rx_empty;
        CData/*3:0*/ tx_level;
        CData/*3:0*/ rx_level;
        CData/*3:0*/ tx_wc;
        CData/*3:0*/ rx_wc;
        CData/*3:0*/ txftlr;
        CData/*3:0*/ rxftlr;
        CData/*3:0*/ eff_cfs;
        CData/*3:0*/ ser;
        CData/*0:0*/ ssienr;
        CData/*2:0*/ mwcr;
        CData/*5:0*/ imr;
        CData/*5:0*/ isr;
        CData/*5:0*/ risr;
        CData/*0:0*/ fifo_rst_n;
        CData/*0:0*/ ssi_sleep;
    };
    struct {
        CData/*0:0*/ cov_scpol_active;
        CData/*0:0*/ set0_imr5;
        CData/*0:0*/ set1_imr5;
        CData/*0:0*/ rdec_icr_en;
        CData/*0:0*/ rdec_txoicr_en;
        CData/*0:0*/ rdec_rxoicr_en;
        CData/*0:0*/ rdec_rxuicr_en;
        CData/*0:0*/ rdec_msticr_en;
        CData/*4:0*/ dfs;
        CData/*1:0*/ frf;
        CData/*0:0*/ scph;
        CData/*0:0*/ scpol;
        CData/*1:0*/ tmod;
        CData/*0:0*/ slv_oe;
        CData/*0:0*/ srl_test;
        CData/*0:0*/ ss_tgl_en;
        CData/*0:0*/ u_regfile__DOT__clk;
        CData/*0:0*/ u_regfile__DOT__resetn;
        CData/*0:0*/ u_regfile__DOT__reg_we;
        CData/*5:0*/ u_regfile__DOT__reg_addr;
        CData/*0:0*/ u_regfile__DOT__reg_re;
        CData/*0:0*/ u_regfile__DOT__fsm_busy;
        CData/*0:0*/ u_regfile__DOT__fsm_sleep;
        CData/*0:0*/ u_regfile__DOT__fsm_multi_mst;
        CData/*0:0*/ u_regfile__DOT__mst_contention;
        CData/*0:0*/ u_regfile__DOT__multi_mst_sync;
        CData/*0:0*/ u_regfile__DOT__start_xfer;
        CData/*0:0*/ u_regfile__DOT__baud2;
        CData/*0:0*/ u_regfile__DOT__sclk_active;
        CData/*3:0*/ u_regfile__DOT__ser;
        CData/*0:0*/ u_regfile__DOT__set0_imr5;
        CData/*0:0*/ u_regfile__DOT__set1_imr5;
        CData/*0:0*/ u_regfile__DOT__tx_push;
        CData/*0:0*/ u_regfile__DOT__rx_pop;
        CData/*0:0*/ u_regfile__DOT__tx_pop;
        CData/*3:0*/ u_regfile__DOT__tx_fifo_wc;
        CData/*3:0*/ u_regfile__DOT__rx_fifo_wc;
        CData/*0:0*/ u_regfile__DOT__fifo_rst_n;
        CData/*0:0*/ u_regfile__DOT__tx_full;
        CData/*0:0*/ u_regfile__DOT__tx_empty;
        CData/*0:0*/ u_regfile__DOT__rx_full;
        CData/*0:0*/ u_regfile__DOT__rx_empty;
        CData/*0:0*/ u_regfile__DOT__ssi_sleep;
        CData/*0:0*/ u_regfile__DOT__ssienr;
        CData/*2:0*/ u_regfile__DOT__mwcr;
        CData/*3:0*/ u_regfile__DOT__txftlr;
        CData/*3:0*/ u_regfile__DOT__rxftlr;
        CData/*5:0*/ u_regfile__DOT__isr;
        CData/*5:0*/ u_regfile__DOT__risr;
        CData/*0:0*/ u_regfile__DOT__rdec_icr_en;
        CData/*0:0*/ u_regfile__DOT__rdec_txoicr_en;
        CData/*0:0*/ u_regfile__DOT__rdec_rxoicr_en;
        CData/*0:0*/ u_regfile__DOT__rdec_rxuicr_en;
        CData/*0:0*/ u_regfile__DOT__rdec_msticr_en;
        CData/*0:0*/ u_regfile__DOT__tx_overflow;
        CData/*5:0*/ u_regfile__DOT__imr;
        CData/*3:0*/ u_regfile__DOT__spec_cfs_min;
        CData/*3:0*/ u_regfile__DOT__spec_txftlr_dflt;
        CData/*4:0*/ u_regfile__DOT__cov_dfs;
        CData/*4:0*/ u_regfile__DOT__cov_eff_dfs;
        CData/*3:0*/ u_regfile__DOT__cov_cfs;
        CData/*3:0*/ u_regfile__DOT__cov_eff_cfs;
        CData/*1:0*/ u_regfile__DOT__cov_frf;
        CData/*0:0*/ u_regfile__DOT__cov_scph;
    };
    struct {
        CData/*0:0*/ u_regfile__DOT__cov_scpol;
        CData/*1:0*/ u_regfile__DOT__cov_tmod;
        CData/*0:0*/ u_regfile__DOT__cov_srl_test;
        CData/*0:0*/ u_regfile__DOT__cov_ss_tgl_en;
        CData/*0:0*/ u_regfile__DOT__cov_slv_oe;
        CData/*3:0*/ u_regfile__DOT__cov_ser;
        CData/*0:0*/ u_regfile__DOT__cov_baud2;
        CData/*0:0*/ u_regfile__DOT__cov_s2;
        CData/*0:0*/ u_regfile__DOT__cov_ssi_busy;
        CData/*0:0*/ u_regfile__DOT__cov_ssi_sleep;
        CData/*0:0*/ u_regfile__DOT__cov_multi_mst_sync;
        CData/*0:0*/ u_regfile__DOT__cov_s1;
        CData/*0:0*/ u_regfile__DOT__cov_start_xfer;
        CData/*0:0*/ u_regfile__DOT__cov_tx_push;
        CData/*0:0*/ u_regfile__DOT__cov_tx_pop;
        CData/*0:0*/ u_regfile__DOT__cov_txftlr;
        CData/*0:0*/ u_regfile__DOT__dr_en_w;
        CData/*0:0*/ u_regfile__DOT__rdec_dr_en;
        CData/*0:0*/ u_regfile__DOT__tx_push_c;
        CData/*0:0*/ u_regfile__DOT__tx_empty_early;
        CData/*0:0*/ u_regfile__DOT__slv_sel;
        CData/*0:0*/ u_regfile__DOT__tx_fifo_ready;
        CData/*0:0*/ u_regfile__DOT__ctrlr0_we;
        CData/*0:0*/ u_regfile__DOT__ctrlr1_we;
        CData/*0:0*/ u_regfile__DOT__ssienr_we;
        CData/*0:0*/ u_regfile__DOT__mwcr_we;
        CData/*0:0*/ u_regfile__DOT__ser_we;
        CData/*0:0*/ u_regfile__DOT__baudr_we;
        CData/*0:0*/ u_regfile__DOT__txftlr_we;
        CData/*0:0*/ u_regfile__DOT__rxftlr_we;
        CData/*0:0*/ u_regfile__DOT__dr_we;
        CData/*0:0*/ u_regfile__DOT__imr_we;
        CData/*2:0*/ u_regfile__DOT__mwcr_ir;
        CData/*3:0*/ u_regfile__DOT__ser_ir;
        CData/*5:0*/ u_regfile__DOT__imr_ir;
        CData/*3:0*/ u_regfile__DOT__txflr;
        CData/*3:0*/ u_regfile__DOT__rxflr;
        CData/*0:0*/ u_regfile__DOT__dcol;
        CData/*0:0*/ u_regfile__DOT__fsm_busy_sr;
        CData/*0:0*/ u_regfile__DOT__multi_mst_edge;
        CData/*0:0*/ u_regfile__DOT__ssi_sleep_ir;
        CData/*0:0*/ u_intctl__DOT__clk;
        CData/*0:0*/ u_intctl__DOT__resetn;
        CData/*5:0*/ u_intctl__DOT__imr;
        CData/*0:0*/ u_intctl__DOT__rdec_rxoicr_en;
        CData/*0:0*/ u_intctl__DOT__rdec_txoicr_en;
        CData/*0:0*/ u_intctl__DOT__rdec_rxuicr_en;
        CData/*0:0*/ u_intctl__DOT__rdec_msticr_en;
        CData/*0:0*/ u_intctl__DOT__rdec_icr_en;
        CData/*0:0*/ u_intctl__DOT__rd_en;
        CData/*0:0*/ u_intctl__DOT__tx_empty;
        CData/*0:0*/ u_intctl__DOT__tx_overflow;
        CData/*0:0*/ u_intctl__DOT__rx_underflow;
        CData/*0:0*/ u_intctl__DOT__rx_full;
        CData/*0:0*/ u_intctl__DOT__rx_overflow;
        CData/*0:0*/ u_intctl__DOT__multi_mst_sync;
        CData/*0:0*/ u_intctl__DOT__set0_imr5;
        CData/*0:0*/ u_intctl__DOT__set1_imr5;
        CData/*0:0*/ u_intctl__DOT__ssi_en;
        CData/*0:0*/ u_intctl__DOT__ssi_txe_intr;
        CData/*0:0*/ u_intctl__DOT__ssi_txo_intr;
        CData/*0:0*/ u_intctl__DOT__ssi_rxu_intr;
        CData/*0:0*/ u_intctl__DOT__ssi_rxf_intr;
        CData/*0:0*/ u_intctl__DOT__ssi_rxo_intr;
    };
    struct {
        CData/*0:0*/ u_intctl__DOT__ssi_mst_intr;
        CData/*0:0*/ u_intctl__DOT__mst_contention;
        CData/*5:0*/ u_intctl__DOT__risr;
        CData/*5:0*/ u_intctl__DOT__isr;
        CData/*0:0*/ u_intctl__DOT__irisr_rx_full;
        CData/*0:0*/ u_intctl__DOT__irisr_rx_fifo_overflow;
        CData/*0:0*/ u_intctl__DOT__irisr_rx_fifo_underflow;
        CData/*0:0*/ u_intctl__DOT__irisr_tx_fifo_overflow;
        CData/*0:0*/ u_intctl__DOT__irisr_tx_empty;
        CData/*0:0*/ u_intctl__DOT__irisr_mst_collision;
        CData/*5:0*/ u_intctl__DOT__irisr;
        CData/*0:0*/ u_fifo__DOT__clk;
        CData/*0:0*/ u_fifo__DOT__rst_n;
        CData/*0:0*/ u_fifo__DOT__fifo_rst_n;
        CData/*0:0*/ u_fifo__DOT__tx_push;
        CData/*0:0*/ u_fifo__DOT__tx_pop;
        CData/*0:0*/ u_fifo__DOT__rx_push;
        CData/*0:0*/ u_fifo__DOT__rx_pop;
        CData/*0:0*/ u_fifo__DOT__tx_full;
        CData/*0:0*/ u_fifo__DOT__tx_empty;
        CData/*0:0*/ u_fifo__DOT__rx_full;
        CData/*0:0*/ u_fifo__DOT__rx_empty;
        CData/*0:0*/ u_fifo__DOT__rx_overflow;
        CData/*0:0*/ u_fifo__DOT__rx_underflow;
        CData/*3:0*/ u_fifo__DOT__tx_level;
        CData/*3:0*/ u_fifo__DOT__rx_level;
        CData/*3:0*/ u_fifo__DOT__tx_rd;
        CData/*3:0*/ u_fifo__DOT__tx_wr;
        CData/*3:0*/ u_fifo__DOT__rx_rd;
        CData/*3:0*/ u_fifo__DOT__rx_wr;
        CData/*0:0*/ u_fifo__DOT__tx_full_w;
        CData/*0:0*/ u_fifo__DOT__tx_empty_w;
        CData/*0:0*/ u_fifo__DOT__rx_full_w;
        CData/*0:0*/ u_fifo__DOT__rx_empty_w;
        CData/*0:0*/ u_sclkgen__DOT__clk;
        CData/*0:0*/ u_sclkgen__DOT__rst_n;
        CData/*0:0*/ u_sclkgen__DOT__sclk_mask;
        CData/*0:0*/ u_sclkgen__DOT__sclk_active;
        CData/*0:0*/ u_sclkgen__DOT__ssi_en;
        CData/*0:0*/ u_sclkgen__DOT__sclk_out;
        CData/*0:0*/ u_sclkgen__DOT__sclk_re;
        CData/*0:0*/ u_sclkgen__DOT__sclk_fe;
        CData/*0:0*/ u_sclkgen__DOT__sclk_active_sync;
        CData/*0:0*/ u_sclkgen__DOT__sclk_re_ir;
        CData/*0:0*/ u_sclkgen__DOT__sclk_fe_ir;
        CData/*0:0*/ u_mstfsm__DOT__clk;
        CData/*0:0*/ u_mstfsm__DOT__rst_n;
        CData/*0:0*/ u_mstfsm__DOT__ssi_en;
        CData/*0:0*/ u_mstfsm__DOT__start_xfer;
        CData/*0:0*/ u_mstfsm__DOT__tx_empty;
        CData/*0:0*/ u_mstfsm__DOT__sclk_re;
        CData/*0:0*/ u_mstfsm__DOT__sclk_fe;
        CData/*2:0*/ u_mstfsm__DOT__mwcr;
        CData/*1:0*/ u_mstfsm__DOT__frf;
        CData/*0:0*/ u_mstfsm__DOT__scph;
        CData/*0:0*/ u_mstfsm__DOT__ss_tgl_en;
        CData/*1:0*/ u_mstfsm__DOT__tmod;
        CData/*4:0*/ u_mstfsm__DOT__dfs;
        CData/*3:0*/ u_mstfsm__DOT__cfs;
        CData/*0:0*/ u_mstfsm__DOT__srl_test;
        CData/*0:0*/ u_mstfsm__DOT__baud2;
        CData/*0:0*/ u_mstfsm__DOT__ss_in_n;
        CData/*0:0*/ u_mstfsm__DOT__rxd;
        CData/*3:0*/ u_mstfsm__DOT__tx_fifo_level;
    };
    struct {
        CData/*3:0*/ u_mstfsm__DOT__txfthr;
        CData/*3:0*/ u_mstfsm__DOT__spec_hold_ss;
        CData/*0:0*/ u_mstfsm__DOT__fsm_busy;
        CData/*0:0*/ u_mstfsm__DOT__fsm_slv_sel;
        CData/*0:0*/ u_mstfsm__DOT__sclk_mask;
        CData/*0:0*/ u_mstfsm__DOT__ssi_oe_n;
        CData/*0:0*/ u_mstfsm__DOT__fsm_sleep;
        CData/*0:0*/ u_mstfsm__DOT__load_tx_shift;
        CData/*0:0*/ u_mstfsm__DOT__ssp_load_tx_shift;
        CData/*0:0*/ u_mstfsm__DOT__load_tx_buffer;
        CData/*0:0*/ u_mstfsm__DOT__load_rx_buf;
        CData/*0:0*/ u_mstfsm__DOT__tx_shift_en;
        CData/*4:0*/ u_mstfsm__DOT__tx_dfs;
        CData/*0:0*/ u_mstfsm__DOT__rx_shift_en;
        CData/*0:0*/ u_mstfsm__DOT__fsm_multi_mst;
        CData/*0:0*/ u_mstfsm__DOT__load_start_bit;
        CData/*3:0*/ u_mstfsm__DOT__cov_fsm_state_id;
        CData/*5:0*/ u_mstfsm__DOT__cov_bit_cnt;
        CData/*3:0*/ u_mstfsm__DOT__cov_ctrl_cnt;
        CData/*0:0*/ u_mstfsm__DOT__cov_f_done;
        CData/*0:0*/ u_mstfsm__DOT__cov_c_done;
        CData/*0:0*/ u_mstfsm__DOT__cov_x_done;
        CData/*0:0*/ u_mstfsm__DOT__cov_last_frame;
        CData/*0:0*/ u_mstfsm__DOT__cov_tx_shift_en;
        CData/*0:0*/ u_mstfsm__DOT__cov_rx_shift_en;
        CData/*0:0*/ u_mstfsm__DOT__cov_load_tx_shift;
        CData/*0:0*/ u_mstfsm__DOT__cov_load_tx_buffer;
        CData/*0:0*/ u_mstfsm__DOT__cov_load_rx_buf;
        CData/*0:0*/ u_mstfsm__DOT__cov_s3;
        CData/*3:0*/ u_mstfsm__DOT__cov_hold_ss_cnt;
        CData/*0:0*/ u_mstfsm__DOT__cov_spi0_control;
        CData/*0:0*/ u_mstfsm__DOT__cov_spi1_control;
        CData/*0:0*/ u_mstfsm__DOT__cov_fsm_busy;
        CData/*0:0*/ u_mstfsm__DOT__cov_fsm_sleep;
        CData/*0:0*/ u_mstfsm__DOT__cov_start_bit_ctl;
        CData/*0:0*/ u_mstfsm__DOT__cov_s0;
        CData/*5:0*/ u_mstfsm__DOT__bit_cnt;
        CData/*3:0*/ u_mstfsm__DOT__ctrl_cnt;
        CData/*0:0*/ u_mstfsm__DOT__last_frame;
        CData/*0:0*/ u_mstfsm__DOT__x_done_1d;
        CData/*0:0*/ u_mstfsm__DOT__tx_load_en;
        CData/*0:0*/ u_mstfsm__DOT__c_done_ir;
        CData/*0:0*/ u_mstfsm__DOT__f_done_ir;
        CData/*0:0*/ u_mstfsm__DOT__abort_ir;
        CData/*0:0*/ u_mstfsm__DOT__abort_seen;
        CData/*0:0*/ u_mstfsm__DOT__spi0_control;
        CData/*0:0*/ u_mstfsm__DOT__spi1_control;
        CData/*0:0*/ u_mstfsm__DOT__rxd_sync_1;
        CData/*0:0*/ u_mstfsm__DOT__rxd_sync_2;
        CData/*3:0*/ u_mstfsm__DOT__hold_ss_cnt;
        CData/*0:0*/ u_mstfsm__DOT__ssp;
        CData/*0:0*/ u_mstfsm__DOT__spi0;
        CData/*0:0*/ u_mstfsm__DOT__spi1;
        CData/*0:0*/ u_mstfsm__DOT__mwire;
        CData/*0:0*/ u_mstfsm__DOT__sclk_re_int;
        CData/*0:0*/ u_mstfsm__DOT__sclk_fe_int;
        CData/*0:0*/ u_mstfsm__DOT__tx_fifo_filled;
        CData/*0:0*/ u_mstfsm__DOT__f_done;
        CData/*0:0*/ u_mstfsm__DOT__sspf_done;
        CData/*0:0*/ u_mstfsm__DOT__c_done;
        CData/*0:0*/ u_mstfsm__DOT__x_done;
        CData/*0:0*/ u_mstfsm__DOT__early_last_frame;
        CData/*0:0*/ u_mstfsm__DOT__inc_bit_cnt;
        CData/*0:0*/ u_mstfsm__DOT__clr_bit_cnt;
    };
    struct {
        CData/*0:0*/ u_mstfsm__DOT__inc_ctrl_cnt;
        CData/*0:0*/ u_mstfsm__DOT__clr_ctrl_cnt;
        CData/*0:0*/ u_mstfsm__DOT__inc_frame_cnt;
        CData/*0:0*/ u_mstfsm__DOT__clr_frame_cnt;
        CData/*0:0*/ u_mstfsm__DOT__sclk_mask_int;
        CData/*0:0*/ u_mstfsm__DOT__fsm_sleep_iw;
        CData/*0:0*/ u_mstfsm__DOT__fsm_busy_iw;
        CData/*0:0*/ u_mstfsm__DOT__fsm_multi_mst_iw;
        CData/*0:0*/ u_mstfsm__DOT__ssi_oe_n_iw;
        CData/*0:0*/ u_mstfsm__DOT__rxd_sync;
        CData/*0:0*/ u_mstfsm__DOT__wrong_pol;
        CData/*0:0*/ u_mstfsm__DOT____VdfgTmp_hf2a781db__0;
        CData/*0:0*/ u_mstfsm__DOT____VdfgTmp_h53254bb6__0;
        CData/*0:0*/ u_shift__DOT__clk;
        CData/*0:0*/ u_shift__DOT__rst_n;
        CData/*0:0*/ u_shift__DOT__tx_shift_en;
        CData/*0:0*/ u_shift__DOT__load_tx_buffer;
        CData/*0:0*/ u_shift__DOT__load_start_bit;
        CData/*0:0*/ u_shift__DOT__rx_shift_en;
        CData/*0:0*/ u_shift__DOT__load_rx_buf;
        CData/*0:0*/ u_shift__DOT__load_tx_shift;
        CData/*0:0*/ u_shift__DOT__rxd;
        CData/*4:0*/ u_shift__DOT__dfs;
        CData/*4:0*/ u_shift__DOT__tx_dfs;
        CData/*0:0*/ u_shift__DOT__fsm_slv_sel;
        CData/*3:0*/ u_shift__DOT__ser;
        CData/*1:0*/ u_shift__DOT__frf;
        CData/*0:0*/ u_shift__DOT__srl_test;
        CData/*0:0*/ u_shift__DOT__ssi_en;
        CData/*3:0*/ u_shift__DOT__ss_n;
        CData/*0:0*/ u_shift__DOT__txd;
        CData/*0:0*/ u_shift__DOT__rx_push;
        CData/*0:0*/ u_shift__DOT__tx_pop;
        CData/*0:0*/ u_shift__DOT__rx_push_reg;
        CData/*0:0*/ u_shift__DOT__load_start_bit_ir;
        CData/*0:0*/ u_shift__DOT__rxd_mst_int;
        CData/*0:0*/ u_shift__DOT__ssp_data_valid_iw;
        CData/*0:0*/ u_shift__DOT__i_rx_shift_en;
        CData/*0:0*/ u_shift__DOT__i_load_rx_buf;
        VL_OUT16(cov_fsm_state,14,0);
        VL_OUT16(cov_baudr,15,0);
        SData/*15:0*/ u_regfile__DOT__baudr;
        SData/*15:0*/ u_regfile__DOT__ctrlr1;
        SData/*15:0*/ u_sclkgen__DOT__baudr;
        SData/*14:0*/ u_sclkgen__DOT__r_det;
        SData/*15:0*/ u_sclkgen__DOT__f_det;
        SData/*15:0*/ u_sclkgen__DOT__ssi_cnt;
        SData/*14:0*/ u_mstfsm__DOT__cov_fsm_state;
        SData/*14:0*/ u_mstfsm__DOT__c_state;
        SData/*14:0*/ u_mstfsm__DOT__n_state;
        VL_IN(reg_wdata,31,0);
        VL_OUT(reg_rdata,31,0);
        VL_OUT(cov_frame_cnt,16,0);
        VL_OUT(cov_ndf,16,0);
        VL_OUT(cov_rx_data,31,0);
        IData/*31:0*/ tx_push_data;
        IData/*31:0*/ tx_pop_data;
        IData/*31:0*/ rx_pop_data;
        IData/*31:0*/ rx_push_data;
        IData/*19:0*/ ctrlr0;
        IData/*16:0*/ ndf;
        IData/*31:0*/ u_regfile__DOT__reg_wdata;
        IData/*31:0*/ u_regfile__DOT__reg_rdata;
        IData/*19:0*/ u_regfile__DOT__ctrlr0;
    };
    struct {
        IData/*16:0*/ u_regfile__DOT__ndf;
        IData/*31:0*/ u_regfile__DOT__tx_push_data;
        IData/*31:0*/ u_regfile__DOT__rx_pop_data;
        IData/*16:0*/ u_regfile__DOT__cov_ndf;
        IData/*19:0*/ u_regfile__DOT__ctrlr0_ir;
        IData/*31:0*/ u_fifo__DOT__tx_push_data;
        IData/*31:0*/ u_fifo__DOT__rx_push_data;
        IData/*31:0*/ u_fifo__DOT__tx_pop_data;
        IData/*31:0*/ u_fifo__DOT__rx_pop_data;
        IData/*16:0*/ u_mstfsm__DOT__ndf;
        IData/*16:0*/ u_mstfsm__DOT__cov_frame_cnt;
        IData/*16:0*/ u_mstfsm__DOT__frame_cnt;
        IData/*31:0*/ u_shift__DOT__tx_pop_data;
        IData/*31:0*/ u_shift__DOT__rx_push_data;
        IData/*31:0*/ u_shift__DOT__tx_shift_reg;
        IData/*31:0*/ u_shift__DOT__tx_buffer;
        IData/*31:0*/ u_shift__DOT__rx_shift_reg;
        IData/*31:0*/ u_shift__DOT__rx_buffer;
        VlUnpacked<IData/*31:0*/, 8> u_fifo__DOT__tx_mem;
        VlUnpacked<IData/*31:0*/, 8> u_fifo__DOT__rx_mem;
    };

    // INTERNAL VARIABLES
    Vspi_m_top__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*5:0*/ u_regfile__DOT__A_CTRLR0 = 0U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_CTRLR1 = 1U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_SSIENR = 2U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_MWCR = 3U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_SER = 4U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_BAUDR = 5U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_TXFTLR = 6U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_RXFTLR = 7U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_TXFLR = 8U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_RXFLR = 9U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_SR = 0x0aU;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_IMR = 0x0bU;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_ISR = 0x0cU;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_RISR = 0x0dU;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_TXOICR = 0x0eU;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_RXOICR = 0x0fU;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_RXUICR = 0x10U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_MSTICR = 0x11U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_ICR = 0x12U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_IDR = 0x16U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_VIDR = 0x17U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_DR_LO = 0x18U;
    static constexpr CData/*5:0*/ u_regfile__DOT__A_DR_HI = 0x3bU;
    static constexpr CData/*3:0*/ u_fifo__DOT__DEPTH = 8U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_IDLE = 1U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_ASSERT_SS = 2U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_POP_TX = 4U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_SHIFT_CTRL = 8U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_SHIFT_BIT = 0x0010U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_PUSH_RX = 0x0020U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_TOGGLE_SS = 0x0040U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_HOLD_MASK = 0x0080U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_MASK_SCLK = 0x0100U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_HOLD_SS = 0x0200U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_CLEAR_SS = 0x0400U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_SLEEP = 0x0800U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_MWPOP = 0x1000U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_WAIT_READY = 0x2000U;
    static constexpr SData/*14:0*/ u_mstfsm__DOT__P_CLEAR_READY = 0x4000U;
    static constexpr IData/*31:0*/ u_regfile__DOT__IDR_VAL = 0x53315f31U;
    static constexpr IData/*31:0*/ u_regfile__DOT__VIDR_VAL = 0x01020101U;

    // CONSTRUCTORS
    Vspi_m_top_spi_m_top(Vspi_m_top__Syms* symsp, const char* v__name);
    ~Vspi_m_top_spi_m_top();
    VL_UNCOPYABLE(Vspi_m_top_spi_m_top);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
