// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vspi_xfer_top.h for the primary calling header

#ifndef VERILATED_VSPI_XFER_TOP_SPI_XFER_TOP_H_
#define VERILATED_VSPI_XFER_TOP_SPI_XFER_TOP_H_  // guard

#include "verilated.h"


class Vspi_xfer_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vspi_xfer_top_spi_xfer_top final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(reg_we,0,0);
        VL_IN8(reg_addr,3,0);
        VL_IN8(reg_re,0,0);
        VL_IN8(rxd,0,0);
        VL_IN8(ss_in_n,0,0);
        VL_OUT8(sclk_out,0,0);
        VL_OUT8(txd,0,0);
        VL_OUT8(ss_n,3,0);
        VL_OUT8(ssi_busy,0,0);
        VL_IN8(SPEC_DFS_MIN,3,0);
        VL_IN8(SPEC_HOLD_SS,3,0);
        VL_OUT8(cov_fsm_state_id,3,0);
        VL_OUT8(cov_sclk_re,0,0);
        VL_OUT8(cov_sclk_fe,0,0);
        VL_OUT8(cov_sclk_out,0,0);
        VL_OUT8(cov_sclk_mask,0,0);
        VL_OUT8(cov_bit_cnt,5,0);
        VL_OUT8(cov_x_done,0,0);
        VL_OUT8(cov_last_frame,0,0);
        VL_OUT8(cov_tx_shift_en,0,0);
        VL_OUT8(cov_rx_shift_en,0,0);
        VL_OUT8(cov_load_tx_shift,0,0);
        VL_OUT8(cov_load_rx_buf,0,0);
        VL_OUT8(cov_ss_active,0,0);
        VL_OUT8(cov_xfer_complete,0,0);
        VL_OUT8(cov_txd,0,0);
        VL_OUT8(cov_dfs,4,0);
        VL_OUT8(cov_eff_dfs,5,0);
        VL_OUT8(cov_baud2,0,0);
        VL_OUT8(cov_tmod,1,0);
        VL_OUT8(cov_frf,1,0);
        VL_OUT8(cov_scph,0,0);
        VL_OUT8(cov_scpol,0,0);
        VL_OUT8(cov_srl_test,0,0);
        VL_OUT8(cov_ss_tgl_en,0,0);
        VL_OUT8(cov_ser,3,0);
        VL_OUT8(cov_tx_level,3,0);
        VL_OUT8(cov_rx_level,3,0);
        VL_OUT8(cov_tx_empty,0,0);
        VL_OUT8(cov_tx_full,0,0);
        VL_OUT8(cov_rx_empty,0,0);
        VL_OUT8(cov_rx_full,0,0);
        VL_OUT8(cov_hold_ss_cnt,3,0);
        VL_OUT8(cov_s0,0,0);
        VL_OUT8(cov_s1,0,0);
        VL_OUT8(cov_s2,0,0);
        VL_OUT8(cov_ss_in_n,0,0);
        VL_OUT8(cov_start_xfer,0,0);
        CData/*0:0*/ sclk_re;
        CData/*0:0*/ sclk_fe;
        CData/*0:0*/ sclk_mask;
        CData/*0:0*/ fsm_slv_sel;
        CData/*0:0*/ load_tx_shift;
        CData/*0:0*/ load_tx_buffer;
        CData/*0:0*/ load_rx_buf;
        CData/*0:0*/ tx_shift_en;
        CData/*0:0*/ rx_shift_en;
        CData/*5:0*/ tx_dfs;
        CData/*0:0*/ ssi_oe_n;
        CData/*0:0*/ fsm_busy;
        CData/*0:0*/ fsm_sleep;
        CData/*0:0*/ tx_pop;
    };
    struct {
        CData/*0:0*/ rx_push;
        CData/*0:0*/ tx_push;
        CData/*0:0*/ rx_pop;
        CData/*0:0*/ tx_full;
        CData/*0:0*/ tx_empty;
        CData/*0:0*/ rx_full;
        CData/*0:0*/ rx_empty;
        CData/*3:0*/ tx_level;
        CData/*3:0*/ rx_level;
        CData/*3:0*/ fsm_c_state;
        CData/*0:0*/ start_xfer;
        CData/*0:0*/ baud2;
        CData/*0:0*/ ssienr;
        CData/*3:0*/ ser;
        CData/*3:0*/ txftlr;
        CData/*4:0*/ dfs;
        CData/*1:0*/ frf;
        CData/*0:0*/ scph;
        CData/*0:0*/ scpol;
        CData/*1:0*/ tmod;
        CData/*0:0*/ srl_test;
        CData/*0:0*/ ss_tgl_en;
        CData/*5:0*/ dfs_dec;
        CData/*5:0*/ dfs_eff;
        CData/*3:0*/ prev_fsm_state;
        CData/*0:0*/ write_active_r;
        CData/*0:0*/ u_regfile__DOT__clk;
        CData/*0:0*/ u_regfile__DOT__rst_n;
        CData/*0:0*/ u_regfile__DOT__reg_we;
        CData/*3:0*/ u_regfile__DOT__reg_addr;
        CData/*0:0*/ u_regfile__DOT__reg_re;
        CData/*0:0*/ u_regfile__DOT__ssienr;
        CData/*3:0*/ u_regfile__DOT__ser;
        CData/*3:0*/ u_regfile__DOT__txftlr;
        CData/*0:0*/ u_regfile__DOT__fsm_busy;
        CData/*0:0*/ u_regfile__DOT__tx_full;
        CData/*0:0*/ u_regfile__DOT__tx_empty;
        CData/*3:0*/ u_regfile__DOT__tx_level;
        CData/*0:0*/ u_regfile__DOT__rx_full;
        CData/*0:0*/ u_regfile__DOT__rx_empty;
        CData/*3:0*/ u_regfile__DOT__rx_level;
        CData/*0:0*/ u_regfile__DOT__tx_pop;
        CData/*0:0*/ u_regfile__DOT__tx_push;
        CData/*0:0*/ u_regfile__DOT__rx_pop;
        CData/*0:0*/ u_regfile__DOT__start_xfer;
        CData/*0:0*/ u_regfile__DOT__slv_sel;
        CData/*0:0*/ u_regfile__DOT__tx_empty_early;
        CData/*0:0*/ u_regfile__DOT__tx_fifo_ready;
        CData/*0:0*/ u_fifo__DOT__clk;
        CData/*0:0*/ u_fifo__DOT__rst_n;
        CData/*0:0*/ u_fifo__DOT__tx_push;
        CData/*0:0*/ u_fifo__DOT__tx_pop;
        CData/*0:0*/ u_fifo__DOT__rx_push;
        CData/*0:0*/ u_fifo__DOT__rx_pop;
        CData/*0:0*/ u_fifo__DOT__tx_full;
        CData/*0:0*/ u_fifo__DOT__tx_empty;
        CData/*0:0*/ u_fifo__DOT__rx_full;
        CData/*0:0*/ u_fifo__DOT__rx_empty;
        CData/*3:0*/ u_fifo__DOT__tx_level;
        CData/*3:0*/ u_fifo__DOT__rx_level;
        CData/*2:0*/ u_fifo__DOT__tx_wr_ptr;
        CData/*2:0*/ u_fifo__DOT__tx_rd_ptr;
        CData/*2:0*/ u_fifo__DOT__rx_wr_ptr;
        CData/*2:0*/ u_fifo__DOT__rx_rd_ptr;
    };
    struct {
        CData/*3:0*/ u_fifo__DOT__tx_cnt;
        CData/*3:0*/ u_fifo__DOT__rx_cnt;
        CData/*0:0*/ u_fifo__DOT__tx_wr_ok;
        CData/*0:0*/ u_fifo__DOT__tx_rd_ok;
        CData/*0:0*/ u_fifo__DOT__rx_wr_ok;
        CData/*0:0*/ u_fifo__DOT__rx_rd_ok;
        CData/*0:0*/ u_sclkgen__DOT__clk;
        CData/*0:0*/ u_sclkgen__DOT__rst_n;
        CData/*0:0*/ u_sclkgen__DOT__ssi_en;
        CData/*0:0*/ u_sclkgen__DOT__sclk_mask;
        CData/*0:0*/ u_sclkgen__DOT__sclk_active;
        CData/*0:0*/ u_sclkgen__DOT__sclk_out;
        CData/*0:0*/ u_sclkgen__DOT__sclk_re;
        CData/*0:0*/ u_sclkgen__DOT__sclk_fe;
        CData/*0:0*/ u_sclkgen__DOT__sclk_re_ir;
        CData/*0:0*/ u_sclkgen__DOT__sclk_fe_ir;
        CData/*0:0*/ u_mstfsm__DOT__clk;
        CData/*0:0*/ u_mstfsm__DOT__rst_n;
        CData/*0:0*/ u_mstfsm__DOT__ssi_en;
        CData/*0:0*/ u_mstfsm__DOT__start_xfer;
        CData/*0:0*/ u_mstfsm__DOT__tx_empty;
        CData/*3:0*/ u_mstfsm__DOT__tx_fifo_level;
        CData/*3:0*/ u_mstfsm__DOT__txfthr;
        CData/*0:0*/ u_mstfsm__DOT__sclk_re;
        CData/*0:0*/ u_mstfsm__DOT__sclk_fe;
        CData/*1:0*/ u_mstfsm__DOT__frf;
        CData/*0:0*/ u_mstfsm__DOT__scph;
        CData/*1:0*/ u_mstfsm__DOT__tmod;
        CData/*5:0*/ u_mstfsm__DOT__dfs;
        CData/*0:0*/ u_mstfsm__DOT__ss_tgl_en;
        CData/*0:0*/ u_mstfsm__DOT__ss_in_n;
        CData/*0:0*/ u_mstfsm__DOT__baud2;
        CData/*3:0*/ u_mstfsm__DOT__spec_hold_ss;
        CData/*3:0*/ u_mstfsm__DOT__c_state;
        CData/*0:0*/ u_mstfsm__DOT__fsm_busy;
        CData/*0:0*/ u_mstfsm__DOT__fsm_sleep;
        CData/*0:0*/ u_mstfsm__DOT__sclk_mask;
        CData/*0:0*/ u_mstfsm__DOT__fsm_slv_sel;
        CData/*0:0*/ u_mstfsm__DOT__load_tx_shift;
        CData/*0:0*/ u_mstfsm__DOT__load_tx_buffer;
        CData/*0:0*/ u_mstfsm__DOT__load_rx_buf;
        CData/*0:0*/ u_mstfsm__DOT__tx_shift_en;
        CData/*0:0*/ u_mstfsm__DOT__rx_shift_en;
        CData/*5:0*/ u_mstfsm__DOT__tx_dfs;
        CData/*0:0*/ u_mstfsm__DOT__ssi_oe_n;
        CData/*5:0*/ u_mstfsm__DOT__cov_bit_cnt;
        CData/*0:0*/ u_mstfsm__DOT__cov_x_done;
        CData/*0:0*/ u_mstfsm__DOT__cov_last_frame;
        CData/*0:0*/ u_mstfsm__DOT__cov_tx_shift_en;
        CData/*0:0*/ u_mstfsm__DOT__cov_rx_shift_en;
        CData/*0:0*/ u_mstfsm__DOT__cov_load_tx_shift;
        CData/*0:0*/ u_mstfsm__DOT__cov_load_rx_buf;
        CData/*3:0*/ u_mstfsm__DOT__cov_hold_ss_cnt;
        CData/*0:0*/ u_mstfsm__DOT__cov_s0;
        CData/*0:0*/ u_mstfsm__DOT__cov_s1;
        CData/*0:0*/ u_mstfsm__DOT__spi0;
        CData/*0:0*/ u_mstfsm__DOT__spi1;
        CData/*0:0*/ u_mstfsm__DOT__ssp;
        CData/*0:0*/ u_mstfsm__DOT__sclk_re_int;
        CData/*0:0*/ u_mstfsm__DOT__sclk_fe_int;
        CData/*5:0*/ u_mstfsm__DOT__bit_cnt;
        CData/*0:0*/ u_mstfsm__DOT__last_frame;
        CData/*0:0*/ u_mstfsm__DOT__x_done_1d;
        CData/*0:0*/ u_mstfsm__DOT__tx_load_en;
    };
    struct {
        CData/*0:0*/ u_mstfsm__DOT__abort_ir;
        CData/*3:0*/ u_mstfsm__DOT__hold_cnt;
        CData/*3:0*/ u_mstfsm__DOT__n_state;
        CData/*5:0*/ u_mstfsm__DOT__dfs_eff;
        CData/*0:0*/ u_mstfsm__DOT__f_done;
        CData/*0:0*/ u_mstfsm__DOT__sspf_done;
        CData/*0:0*/ u_mstfsm__DOT__tx_fifo_filled;
        CData/*0:0*/ u_mstfsm__DOT__x_done;
        CData/*0:0*/ u_mstfsm__DOT__inc_bit_cnt;
        CData/*0:0*/ u_mstfsm__DOT__clr_bit_cnt;
        CData/*0:0*/ u_mstfsm__DOT__inc_frame_cnt;
        CData/*0:0*/ u_mstfsm__DOT__clr_frame_cnt;
        CData/*0:0*/ u_mstfsm__DOT__abort_now;
        CData/*0:0*/ u_mstfsm__DOT__busy_now;
        CData/*0:0*/ u_mstfsm__DOT__refill_now;
        CData/*0:0*/ u_mstfsm__DOT__abort_seen_r;
        CData/*0:0*/ u_mstfsm__DOT__refill_seen_r;
        CData/*0:0*/ u_mstfsm__DOT__fsm_sleep_ir;
        CData/*0:0*/ u_mstfsm__DOT__fsm_busy_ir;
        CData/*0:0*/ u_mstfsm__DOT__rx_load_gate;
        CData/*0:0*/ u_mstfsm__DOT__ssi_oe_n_iw;
        CData/*0:0*/ u_mstfsm__DOT__ssi_oe_n_ir;
        CData/*0:0*/ u_mstfsm__DOT____VdfgTmp_hf2822343__0;
        CData/*0:0*/ u_mstfsm__DOT____VdfgTmp_hc03193b8__0;
        CData/*0:0*/ u_mstfsm__DOT____VdfgTmp_h0e46c02e__0;
        CData/*0:0*/ u_mstfsm__DOT____VdfgTmp_hdb116fd1__0;
        CData/*0:0*/ u_shift__DOT__clk;
        CData/*0:0*/ u_shift__DOT__rst_n;
        CData/*0:0*/ u_shift__DOT__tx_shift_en;
        CData/*0:0*/ u_shift__DOT__load_tx_shift;
        CData/*0:0*/ u_shift__DOT__load_tx_buffer;
        CData/*0:0*/ u_shift__DOT__rx_shift_en;
        CData/*0:0*/ u_shift__DOT__load_rx_buf;
        CData/*0:0*/ u_shift__DOT__rxd;
        CData/*5:0*/ u_shift__DOT__dfs;
        CData/*0:0*/ u_shift__DOT__fsm_slv_sel;
        CData/*3:0*/ u_shift__DOT__ser;
        CData/*1:0*/ u_shift__DOT__frf;
        CData/*0:0*/ u_shift__DOT__srl_test;
        CData/*0:0*/ u_shift__DOT__ssi_en;
        CData/*0:0*/ u_shift__DOT__txd;
        CData/*0:0*/ u_shift__DOT__tx_pop;
        CData/*0:0*/ u_shift__DOT__rx_push;
        CData/*3:0*/ u_shift__DOT__ss_n;
        CData/*0:0*/ u_shift__DOT__cov_txd;
        CData/*0:0*/ u_shift__DOT__tx_pop_ir;
        CData/*0:0*/ u_shift__DOT__rx_push_ir;
        CData/*0:0*/ u_shift__DOT__rxd_mst_int;
        VL_OUT16(cov_fsm_state,10,0);
        VL_OUT16(cov_baudr,15,0);
        SData/*15:0*/ baudr;
        SData/*15:0*/ u_regfile__DOT__baudr;
        SData/*15:0*/ u_sclkgen__DOT__baudr;
        SData/*15:0*/ u_sclkgen__DOT__ssi_cnt_out;
        SData/*15:0*/ u_sclkgen__DOT__ssi_cnt;
        SData/*15:0*/ u_sclkgen__DOT__r_det;
        SData/*15:0*/ u_sclkgen__DOT__f_det;
        SData/*10:0*/ u_mstfsm__DOT__cov_fsm_state;
        VL_IN(reg_wdata,31,0);
        VL_OUT(reg_rdata,31,0);
        VL_OUT(cov_frame_cnt,16,0);
        VL_OUT(cov_ndf,16,0);
        VL_OUT(cov_rx_data,31,0);
        IData/*31:0*/ tx_pop_data;
    };
    struct {
        IData/*31:0*/ rx_pop_data;
        IData/*31:0*/ rx_push_data;
        IData/*31:0*/ ctrlr0;
        IData/*31:0*/ ctrlr1;
        IData/*16:0*/ ndf;
        IData/*31:0*/ u_regfile__DOT__reg_wdata;
        IData/*31:0*/ u_regfile__DOT__reg_rdata;
        IData/*31:0*/ u_regfile__DOT__ctrlr0;
        IData/*31:0*/ u_regfile__DOT__ctrlr1;
        IData/*31:0*/ u_regfile__DOT__rx_pop_data;
        IData/*31:0*/ u_fifo__DOT__tx_push_data;
        IData/*31:0*/ u_fifo__DOT__rx_push_data;
        IData/*31:0*/ u_fifo__DOT__tx_pop_data;
        IData/*31:0*/ u_fifo__DOT__rx_pop_data;
        IData/*16:0*/ u_mstfsm__DOT__ndf;
        IData/*16:0*/ u_mstfsm__DOT__cov_frame_cnt;
        IData/*16:0*/ u_mstfsm__DOT__frame_cnt;
        IData/*31:0*/ u_shift__DOT__tx_pop_data;
        IData/*31:0*/ u_shift__DOT__rx_push_data;
        IData/*31:0*/ u_shift__DOT__cov_rx_buffer;
        IData/*31:0*/ u_shift__DOT__tx_shift_reg;
        IData/*31:0*/ u_shift__DOT__tx_buffer;
        IData/*31:0*/ u_shift__DOT__rx_shift_reg;
        IData/*31:0*/ u_shift__DOT__rx_buffer;
        VlUnpacked<IData/*31:0*/, 8> u_fifo__DOT__tx_mem;
        VlUnpacked<IData/*31:0*/, 8> u_fifo__DOT__rx_mem;
    };

    // INTERNAL VARIABLES
    Vspi_xfer_top__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*3:0*/ u_regfile__DOT__A_CTRLR0 = 0U;
    static constexpr CData/*3:0*/ u_regfile__DOT__A_CTRLR1 = 1U;
    static constexpr CData/*3:0*/ u_regfile__DOT__A_SSIENR = 2U;
    static constexpr CData/*3:0*/ u_regfile__DOT__A_SER = 3U;
    static constexpr CData/*3:0*/ u_regfile__DOT__A_BAUDR = 4U;
    static constexpr CData/*3:0*/ u_regfile__DOT__A_TXFTLR = 5U;
    static constexpr CData/*3:0*/ u_regfile__DOT__A_TXFLR = 6U;
    static constexpr CData/*3:0*/ u_regfile__DOT__A_RXFLR = 7U;
    static constexpr CData/*3:0*/ u_regfile__DOT__A_SR = 8U;
    static constexpr CData/*3:0*/ u_regfile__DOT__A_DR = 9U;
    static constexpr CData/*3:0*/ u_mstfsm__DOT__S_IDLE = 0U;
    static constexpr CData/*3:0*/ u_mstfsm__DOT__S_ASSERT_SS = 1U;
    static constexpr CData/*3:0*/ u_mstfsm__DOT__S_POP_TX = 2U;
    static constexpr CData/*3:0*/ u_mstfsm__DOT__S_SHIFT_BIT = 3U;
    static constexpr CData/*3:0*/ u_mstfsm__DOT__S_PUSH_RX = 4U;
    static constexpr CData/*3:0*/ u_mstfsm__DOT__S_TOGGLE_SS = 5U;
    static constexpr CData/*3:0*/ u_mstfsm__DOT__S_HOLD_MASK = 6U;
    static constexpr CData/*3:0*/ u_mstfsm__DOT__S_MASK_SCLK = 7U;
    static constexpr CData/*3:0*/ u_mstfsm__DOT__S_HOLD_SS = 8U;
    static constexpr CData/*3:0*/ u_mstfsm__DOT__S_CLEAR_SS = 9U;
    static constexpr CData/*3:0*/ u_mstfsm__DOT__S_SLEEP = 0x0aU;
    static constexpr IData/*31:0*/ DFS_W = 5U;
    static constexpr IData/*31:0*/ NDF_W = 0x00000011U;
    static constexpr IData/*31:0*/ BAUDR_W = 0x00000010U;
    static constexpr IData/*31:0*/ NUM_SLAVES = 4U;
    static constexpr IData/*31:0*/ TX_DEPTH = 8U;
    static constexpr IData/*31:0*/ RX_DEPTH = 8U;
    static constexpr IData/*31:0*/ u_fifo__DOT__AW = 3U;
    static constexpr IData/*31:0*/ u_fifo__DOT__DEPTH = 8U;

    // CONSTRUCTORS
    Vspi_xfer_top_spi_xfer_top(Vspi_xfer_top__Syms* symsp, const char* v__name);
    ~Vspi_xfer_top_spi_xfer_top();
    VL_UNCOPYABLE(Vspi_xfer_top_spi_xfer_top);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
