// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vspi_xfer_top__Syms.h"


VL_ATTR_COLD void Vspi_xfer_top___024root__trace_init_sub__TOP__spi_xfer_top__0(Vspi_xfer_top___024root* vlSelf, VerilatedVcd* tracep);

VL_ATTR_COLD void Vspi_xfer_top___024root__trace_init_sub__TOP__0(Vspi_xfer_top___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vspi_xfer_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vspi_xfer_top___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->pushPrefix("spi_xfer_top", VerilatedTracePrefixType::SCOPE_MODULE);
    Vspi_xfer_top___024root__trace_init_sub__TOP__spi_xfer_top__0(vlSelf, tracep);
    tracep->popPrefix();
    tracep->declBit(c+1,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+3,0,"reg_we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+4,0,"reg_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+5,0,"reg_wdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+6,0,"reg_re",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+7,0,"reg_rdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+8,0,"rxd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+9,0,"ss_in_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+10,0,"sclk_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+11,0,"txd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+12,0,"ss_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+13,0,"ssi_busy",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+14,0,"SPEC_DFS_MIN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+15,0,"SPEC_HOLD_SS",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+16,0,"cov_fsm_state",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+17,0,"cov_fsm_state_id",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+18,0,"cov_sclk_re",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+19,0,"cov_sclk_fe",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+20,0,"cov_sclk_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+21,0,"cov_sclk_mask",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+22,0,"cov_bit_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+23,0,"cov_frame_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 16,0);
    tracep->declBit(c+24,0,"cov_x_done",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+25,0,"cov_last_frame",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+26,0,"cov_tx_shift_en",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+27,0,"cov_rx_shift_en",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+28,0,"cov_load_tx_shift",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"cov_load_rx_buf",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+30,0,"cov_ss_active",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+31,0,"cov_xfer_complete",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+32,0,"cov_txd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+33,0,"cov_dfs",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+34,0,"cov_eff_dfs",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+35,0,"cov_baudr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+36,0,"cov_baud2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+37,0,"cov_ndf",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 16,0);
    tracep->declBus(c+38,0,"cov_tmod",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+39,0,"cov_frf",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+40,0,"cov_scph",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+41,0,"cov_scpol",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"cov_srl_test",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"cov_ss_tgl_en",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+44,0,"cov_ser",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+45,0,"cov_tx_level",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+46,0,"cov_rx_level",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+47,0,"cov_tx_empty",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+48,0,"cov_tx_full",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+49,0,"cov_rx_empty",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+50,0,"cov_rx_full",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+51,0,"cov_hold_ss_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+52,0,"cov_s0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+53,0,"cov_s1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"cov_s2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+55,0,"cov_rx_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+56,0,"cov_ss_in_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+57,0,"cov_start_xfer",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
}

VL_ATTR_COLD void Vspi_xfer_top___024root__trace_init_sub__TOP__spi_xfer_top__0(Vspi_xfer_top___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vspi_xfer_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vspi_xfer_top___024root__trace_init_sub__TOP__spi_xfer_top__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBus(c+350,0,"DFS_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+351,0,"NDF_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+352,0,"BAUDR_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+353,0,"NUM_SLAVES",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+354,0,"TX_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+354,0,"RX_DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+58,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+59,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+60,0,"reg_we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+61,0,"reg_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+62,0,"reg_wdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+63,0,"reg_re",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+64,0,"reg_rdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+65,0,"rxd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+66,0,"ss_in_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+67,0,"sclk_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+68,0,"txd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+69,0,"ss_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+70,0,"ssi_busy",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+71,0,"SPEC_DFS_MIN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+72,0,"SPEC_HOLD_SS",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+73,0,"cov_fsm_state",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+74,0,"cov_fsm_state_id",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+75,0,"cov_sclk_re",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+76,0,"cov_sclk_fe",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+77,0,"cov_sclk_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+78,0,"cov_sclk_mask",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+79,0,"cov_bit_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+80,0,"cov_frame_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 16,0);
    tracep->declBit(c+81,0,"cov_x_done",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+82,0,"cov_last_frame",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+83,0,"cov_tx_shift_en",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+84,0,"cov_rx_shift_en",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+85,0,"cov_load_tx_shift",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+86,0,"cov_load_rx_buf",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+87,0,"cov_ss_active",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+88,0,"cov_xfer_complete",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+89,0,"cov_txd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+90,0,"cov_dfs",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+91,0,"cov_eff_dfs",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+92,0,"cov_baudr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+93,0,"cov_baud2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+94,0,"cov_ndf",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 16,0);
    tracep->declBus(c+95,0,"cov_tmod",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+96,0,"cov_frf",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+97,0,"cov_scph",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+98,0,"cov_scpol",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+99,0,"cov_srl_test",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+100,0,"cov_ss_tgl_en",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+101,0,"cov_ser",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+102,0,"cov_tx_level",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+103,0,"cov_rx_level",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+104,0,"cov_tx_empty",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+105,0,"cov_tx_full",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+106,0,"cov_rx_empty",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+107,0,"cov_rx_full",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+108,0,"cov_hold_ss_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+109,0,"cov_s0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+110,0,"cov_s1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+111,0,"cov_s2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+112,0,"cov_rx_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+113,0,"cov_ss_in_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+114,0,"cov_start_xfer",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+115,0,"sclk_re",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+116,0,"sclk_fe",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"sclk_mask",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+118,0,"fsm_slv_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+119,0,"load_tx_shift",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+120,0,"load_tx_buffer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+121,0,"load_rx_buf",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"tx_shift_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+123,0,"rx_shift_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+124,0,"tx_dfs",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBit(c+125,0,"ssi_oe_n",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"fsm_busy",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+127,0,"fsm_sleep",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+128,0,"tx_pop",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+129,0,"rx_push",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+130,0,"tx_push",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"rx_pop",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+132,0,"tx_full",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+133,0,"tx_empty",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+134,0,"rx_full",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"rx_empty",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+136,0,"tx_level",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+137,0,"rx_level",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+138,0,"tx_pop_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+139,0,"rx_pop_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+140,0,"rx_push_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+141,0,"fsm_c_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+142,0,"start_xfer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+143,0,"baud2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+144,0,"ctrlr0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+145,0,"ctrlr1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+146,0,"ssienr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+147,0,"ser",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+148,0,"baudr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+149,0,"txftlr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+150,0,"dfs",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+151,0,"frf",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+152,0,"scph",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+153,0,"scpol",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+154,0,"tmod",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+155,0,"srl_test",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+156,0,"ss_tgl_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+157,0,"ndf",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 16,0);
    tracep->declBus(c+158,0,"dfs_dec",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+159,0,"dfs_eff",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+160,0,"prev_fsm_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+161,0,"write_active_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("u_fifo", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+162,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+163,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+164,0,"tx_push",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+165,0,"tx_push_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+166,0,"tx_pop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+167,0,"rx_push",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+168,0,"rx_push_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+169,0,"rx_pop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+170,0,"tx_full",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+171,0,"tx_empty",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"rx_full",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+173,0,"rx_empty",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+174,0,"tx_level",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+175,0,"rx_level",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+176,0,"tx_pop_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+177,0,"rx_pop_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+355,0,"AW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+354,0,"DEPTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("tx_mem", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 8; ++i) {
        tracep->declBus(c+178+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("rx_mem", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 8; ++i) {
        tracep->declBus(c+186+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+194,0,"tx_wr_ptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+195,0,"tx_rd_ptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+196,0,"rx_wr_ptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+197,0,"rx_rd_ptr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+198,0,"tx_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+199,0,"rx_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+200,0,"tx_wr_ok",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+201,0,"tx_rd_ok",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+202,0,"rx_wr_ok",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+203,0,"rx_rd_ok",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("u_mstfsm", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+204,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+205,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+206,0,"ssi_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+207,0,"start_xfer",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+208,0,"tx_empty",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+209,0,"tx_fifo_level",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+210,0,"txfthr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+211,0,"sclk_re",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+212,0,"sclk_fe",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+213,0,"frf",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+214,0,"scph",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+215,0,"tmod",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+216,0,"dfs",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+217,0,"ndf",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 16,0);
    tracep->declBit(c+218,0,"ss_tgl_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+219,0,"ss_in_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+220,0,"baud2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+221,0,"spec_hold_ss",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+222,0,"c_state",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+223,0,"fsm_busy",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+224,0,"fsm_sleep",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+225,0,"sclk_mask",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+226,0,"fsm_slv_sel",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+227,0,"load_tx_shift",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+228,0,"load_tx_buffer",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+229,0,"load_rx_buf",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+230,0,"tx_shift_en",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+231,0,"rx_shift_en",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+232,0,"tx_dfs",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBit(c+233,0,"ssi_oe_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+234,0,"cov_fsm_state",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+235,0,"cov_bit_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+236,0,"cov_frame_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 16,0);
    tracep->declBit(c+237,0,"cov_x_done",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+238,0,"cov_last_frame",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+239,0,"cov_tx_shift_en",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+240,0,"cov_rx_shift_en",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+241,0,"cov_load_tx_shift",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+242,0,"cov_load_rx_buf",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+243,0,"cov_hold_ss_cnt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+244,0,"cov_s0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+245,0,"cov_s1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+356,0,"S_IDLE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+357,0,"S_ASSERT_SS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+358,0,"S_POP_TX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+359,0,"S_SHIFT_BIT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+360,0,"S_PUSH_RX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+361,0,"S_TOGGLE_SS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+362,0,"S_HOLD_MASK",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+363,0,"S_MASK_SCLK",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+364,0,"S_HOLD_SS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+365,0,"S_CLEAR_SS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+366,0,"S_SLEEP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+246,0,"spi0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+247,0,"spi1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+248,0,"ssp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+249,0,"sclk_re_int",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+250,0,"sclk_fe_int",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+251,0,"bit_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+252,0,"frame_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 16,0);
    tracep->declBit(c+253,0,"last_frame",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+254,0,"x_done_1d",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+255,0,"tx_load_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+256,0,"abort_ir",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+257,0,"hold_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+258,0,"n_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+259,0,"dfs_eff",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBit(c+260,0,"f_done",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+261,0,"sspf_done",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+262,0,"tx_fifo_filled",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+263,0,"x_done",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+264,0,"inc_bit_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+265,0,"clr_bit_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+266,0,"inc_frame_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+267,0,"clr_frame_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+268,0,"abort_now",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+269,0,"busy_now",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+270,0,"refill_now",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+271,0,"abort_seen_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+272,0,"refill_seen_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+273,0,"fsm_sleep_ir",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+274,0,"fsm_busy_ir",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+275,0,"rx_load_gate",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+276,0,"ssi_oe_n_iw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+277,0,"ssi_oe_n_ir",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("u_regfile", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+278,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+279,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+280,0,"reg_we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+281,0,"reg_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+282,0,"reg_wdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+283,0,"reg_re",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+284,0,"reg_rdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+285,0,"ctrlr0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+286,0,"ctrlr1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+287,0,"ssienr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+288,0,"ser",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+289,0,"baudr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+290,0,"txftlr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+291,0,"fsm_busy",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+292,0,"tx_full",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+293,0,"tx_empty",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+294,0,"tx_level",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+295,0,"rx_full",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+296,0,"rx_empty",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+297,0,"rx_level",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+298,0,"rx_pop_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+299,0,"tx_pop",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+300,0,"tx_push",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+301,0,"rx_pop",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+302,0,"start_xfer",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+356,0,"A_CTRLR0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+357,0,"A_CTRLR1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+358,0,"A_SSIENR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+359,0,"A_SER",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+360,0,"A_BAUDR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+361,0,"A_TXFTLR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+362,0,"A_TXFLR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+363,0,"A_RXFLR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+364,0,"A_SR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+365,0,"A_DR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+303,0,"slv_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+304,0,"tx_empty_early",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+305,0,"tx_fifo_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("u_sclkgen", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+306,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+307,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+308,0,"ssi_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+309,0,"baudr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+310,0,"sclk_mask",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+311,0,"sclk_active",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+312,0,"sclk_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+313,0,"sclk_re",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+314,0,"sclk_fe",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+315,0,"ssi_cnt_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+316,0,"ssi_cnt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+317,0,"sclk_re_ir",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+318,0,"sclk_fe_ir",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+319,0,"r_det",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+320,0,"f_det",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->popPrefix();
    tracep->pushPrefix("u_shift", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+321,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+322,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+323,0,"tx_shift_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+324,0,"load_tx_shift",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+325,0,"load_tx_buffer",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+326,0,"rx_shift_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+327,0,"load_rx_buf",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+328,0,"tx_pop_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+329,0,"rxd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+330,0,"dfs",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBit(c+331,0,"fsm_slv_sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+332,0,"ser",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+333,0,"frf",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+334,0,"srl_test",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+335,0,"ssi_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+336,0,"txd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+337,0,"tx_pop",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+338,0,"rx_push",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+339,0,"ss_n",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+340,0,"rx_push_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+341,0,"cov_txd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+342,0,"cov_rx_buffer",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+343,0,"tx_shift_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+344,0,"tx_buffer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+345,0,"rx_shift_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+346,0,"rx_buffer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+347,0,"tx_pop_ir",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+348,0,"rx_push_ir",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+349,0,"rxd_mst_int",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
}

VL_ATTR_COLD void Vspi_xfer_top___024root__trace_init_top(Vspi_xfer_top___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vspi_xfer_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vspi_xfer_top___024root__trace_init_top\n"); );
    // Body
    Vspi_xfer_top___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vspi_xfer_top___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vspi_xfer_top___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vspi_xfer_top___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vspi_xfer_top___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vspi_xfer_top___024root__trace_register(Vspi_xfer_top___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vspi_xfer_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vspi_xfer_top___024root__trace_register\n"); );
    // Body
    tracep->addConstCb(&Vspi_xfer_top___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vspi_xfer_top___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vspi_xfer_top___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vspi_xfer_top___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vspi_xfer_top___024root__trace_const_0_sub_0(Vspi_xfer_top___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vspi_xfer_top___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vspi_xfer_top___024root__trace_const_0\n"); );
    // Init
    Vspi_xfer_top___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vspi_xfer_top___024root*>(voidSelf);
    Vspi_xfer_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vspi_xfer_top___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vspi_xfer_top___024root__trace_const_0_sub_0(Vspi_xfer_top___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vspi_xfer_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vspi_xfer_top___024root__trace_const_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+350,(5U),32);
    bufp->fullIData(oldp+351,(0x11U),32);
    bufp->fullIData(oldp+352,(0x10U),32);
    bufp->fullIData(oldp+353,(4U),32);
    bufp->fullIData(oldp+354,(8U),32);
    bufp->fullIData(oldp+355,(3U),32);
    bufp->fullCData(oldp+356,(0U),4);
    bufp->fullCData(oldp+357,(1U),4);
    bufp->fullCData(oldp+358,(2U),4);
    bufp->fullCData(oldp+359,(3U),4);
    bufp->fullCData(oldp+360,(4U),4);
    bufp->fullCData(oldp+361,(5U),4);
    bufp->fullCData(oldp+362,(6U),4);
    bufp->fullCData(oldp+363,(7U),4);
    bufp->fullCData(oldp+364,(8U),4);
    bufp->fullCData(oldp+365,(9U),4);
    bufp->fullCData(oldp+366,(0xaU),4);
}

VL_ATTR_COLD void Vspi_xfer_top___024root__trace_full_0_sub_0(Vspi_xfer_top___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vspi_xfer_top___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vspi_xfer_top___024root__trace_full_0\n"); );
    // Init
    Vspi_xfer_top___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vspi_xfer_top___024root*>(voidSelf);
    Vspi_xfer_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vspi_xfer_top___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vspi_xfer_top___024root__trace_full_0_sub_0(Vspi_xfer_top___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vspi_xfer_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vspi_xfer_top___024root__trace_full_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelf->clk));
    bufp->fullBit(oldp+2,(vlSelf->rst_n));
    bufp->fullBit(oldp+3,(vlSelf->reg_we));
    bufp->fullCData(oldp+4,(vlSelf->reg_addr),4);
    bufp->fullIData(oldp+5,(vlSelf->reg_wdata),32);
    bufp->fullBit(oldp+6,(vlSelf->reg_re));
    bufp->fullIData(oldp+7,(vlSelf->reg_rdata),32);
    bufp->fullBit(oldp+8,(vlSelf->rxd));
    bufp->fullBit(oldp+9,(vlSelf->ss_in_n));
    bufp->fullBit(oldp+10,(vlSelf->sclk_out));
    bufp->fullBit(oldp+11,(vlSelf->txd));
    bufp->fullCData(oldp+12,(vlSelf->ss_n),4);
    bufp->fullBit(oldp+13,(vlSelf->ssi_busy));
    bufp->fullCData(oldp+14,(vlSelf->SPEC_DFS_MIN),4);
    bufp->fullCData(oldp+15,(vlSelf->SPEC_HOLD_SS),4);
    bufp->fullSData(oldp+16,(vlSelf->cov_fsm_state),11);
    bufp->fullCData(oldp+17,(vlSelf->cov_fsm_state_id),4);
    bufp->fullBit(oldp+18,(vlSelf->cov_sclk_re));
    bufp->fullBit(oldp+19,(vlSelf->cov_sclk_fe));
    bufp->fullBit(oldp+20,(vlSelf->cov_sclk_out));
    bufp->fullBit(oldp+21,(vlSelf->cov_sclk_mask));
    bufp->fullCData(oldp+22,(vlSelf->cov_bit_cnt),6);
    bufp->fullIData(oldp+23,(vlSelf->cov_frame_cnt),17);
    bufp->fullBit(oldp+24,(vlSelf->cov_x_done));
    bufp->fullBit(oldp+25,(vlSelf->cov_last_frame));
    bufp->fullBit(oldp+26,(vlSelf->cov_tx_shift_en));
    bufp->fullBit(oldp+27,(vlSelf->cov_rx_shift_en));
    bufp->fullBit(oldp+28,(vlSelf->cov_load_tx_shift));
    bufp->fullBit(oldp+29,(vlSelf->cov_load_rx_buf));
    bufp->fullBit(oldp+30,(vlSelf->cov_ss_active));
    bufp->fullBit(oldp+31,(vlSelf->cov_xfer_complete));
    bufp->fullBit(oldp+32,(vlSelf->cov_txd));
    bufp->fullCData(oldp+33,(vlSelf->cov_dfs),5);
    bufp->fullCData(oldp+34,(vlSelf->cov_eff_dfs),6);
    bufp->fullSData(oldp+35,(vlSelf->cov_baudr),16);
    bufp->fullBit(oldp+36,(vlSelf->cov_baud2));
    bufp->fullIData(oldp+37,(vlSelf->cov_ndf),17);
    bufp->fullCData(oldp+38,(vlSelf->cov_tmod),2);
    bufp->fullCData(oldp+39,(vlSelf->cov_frf),2);
    bufp->fullBit(oldp+40,(vlSelf->cov_scph));
    bufp->fullBit(oldp+41,(vlSelf->cov_scpol));
    bufp->fullBit(oldp+42,(vlSelf->cov_srl_test));
    bufp->fullBit(oldp+43,(vlSelf->cov_ss_tgl_en));
    bufp->fullCData(oldp+44,(vlSelf->cov_ser),4);
    bufp->fullCData(oldp+45,(vlSelf->cov_tx_level),4);
    bufp->fullCData(oldp+46,(vlSelf->cov_rx_level),4);
    bufp->fullBit(oldp+47,(vlSelf->cov_tx_empty));
    bufp->fullBit(oldp+48,(vlSelf->cov_tx_full));
    bufp->fullBit(oldp+49,(vlSelf->cov_rx_empty));
    bufp->fullBit(oldp+50,(vlSelf->cov_rx_full));
    bufp->fullCData(oldp+51,(vlSelf->cov_hold_ss_cnt),4);
    bufp->fullBit(oldp+52,(vlSelf->cov_s0));
    bufp->fullBit(oldp+53,(vlSelf->cov_s1));
    bufp->fullBit(oldp+54,(vlSelf->cov_s2));
    bufp->fullIData(oldp+55,(vlSelf->cov_rx_data),32);
    bufp->fullBit(oldp+56,(vlSelf->cov_ss_in_n));
    bufp->fullBit(oldp+57,(vlSelf->cov_start_xfer));
    bufp->fullBit(oldp+58,(vlSymsp->TOP__spi_xfer_top.clk));
    bufp->fullBit(oldp+59,(vlSymsp->TOP__spi_xfer_top.rst_n));
    bufp->fullBit(oldp+60,(vlSymsp->TOP__spi_xfer_top.reg_we));
    bufp->fullCData(oldp+61,(vlSymsp->TOP__spi_xfer_top.reg_addr),4);
    bufp->fullIData(oldp+62,(vlSymsp->TOP__spi_xfer_top.reg_wdata),32);
    bufp->fullBit(oldp+63,(vlSymsp->TOP__spi_xfer_top.reg_re));
    bufp->fullIData(oldp+64,(vlSymsp->TOP__spi_xfer_top.reg_rdata),32);
    bufp->fullBit(oldp+65,(vlSymsp->TOP__spi_xfer_top.rxd));
    bufp->fullBit(oldp+66,(vlSymsp->TOP__spi_xfer_top.ss_in_n));
    bufp->fullBit(oldp+67,(vlSymsp->TOP__spi_xfer_top.sclk_out));
    bufp->fullBit(oldp+68,(vlSymsp->TOP__spi_xfer_top.txd));
    bufp->fullCData(oldp+69,(vlSymsp->TOP__spi_xfer_top.ss_n),4);
    bufp->fullBit(oldp+70,(vlSymsp->TOP__spi_xfer_top.ssi_busy));
    bufp->fullCData(oldp+71,(vlSymsp->TOP__spi_xfer_top.SPEC_DFS_MIN),4);
    bufp->fullCData(oldp+72,(vlSymsp->TOP__spi_xfer_top.SPEC_HOLD_SS),4);
    bufp->fullSData(oldp+73,(vlSymsp->TOP__spi_xfer_top.cov_fsm_state),11);
    bufp->fullCData(oldp+74,(vlSymsp->TOP__spi_xfer_top.cov_fsm_state_id),4);
    bufp->fullBit(oldp+75,(vlSymsp->TOP__spi_xfer_top.cov_sclk_re));
    bufp->fullBit(oldp+76,(vlSymsp->TOP__spi_xfer_top.cov_sclk_fe));
    bufp->fullBit(oldp+77,(vlSymsp->TOP__spi_xfer_top.cov_sclk_out));
    bufp->fullBit(oldp+78,(vlSymsp->TOP__spi_xfer_top.cov_sclk_mask));
    bufp->fullCData(oldp+79,(vlSymsp->TOP__spi_xfer_top.cov_bit_cnt),6);
    bufp->fullIData(oldp+80,(vlSymsp->TOP__spi_xfer_top.cov_frame_cnt),17);
    bufp->fullBit(oldp+81,(vlSymsp->TOP__spi_xfer_top.cov_x_done));
    bufp->fullBit(oldp+82,(vlSymsp->TOP__spi_xfer_top.cov_last_frame));
    bufp->fullBit(oldp+83,(vlSymsp->TOP__spi_xfer_top.cov_tx_shift_en));
    bufp->fullBit(oldp+84,(vlSymsp->TOP__spi_xfer_top.cov_rx_shift_en));
    bufp->fullBit(oldp+85,(vlSymsp->TOP__spi_xfer_top.cov_load_tx_shift));
    bufp->fullBit(oldp+86,(vlSymsp->TOP__spi_xfer_top.cov_load_rx_buf));
    bufp->fullBit(oldp+87,(vlSymsp->TOP__spi_xfer_top.cov_ss_active));
    bufp->fullBit(oldp+88,(vlSymsp->TOP__spi_xfer_top.cov_xfer_complete));
    bufp->fullBit(oldp+89,(vlSymsp->TOP__spi_xfer_top.cov_txd));
    bufp->fullCData(oldp+90,(vlSymsp->TOP__spi_xfer_top.cov_dfs),5);
    bufp->fullCData(oldp+91,(vlSymsp->TOP__spi_xfer_top.cov_eff_dfs),6);
    bufp->fullSData(oldp+92,(vlSymsp->TOP__spi_xfer_top.cov_baudr),16);
    bufp->fullBit(oldp+93,(vlSymsp->TOP__spi_xfer_top.cov_baud2));
    bufp->fullIData(oldp+94,(vlSymsp->TOP__spi_xfer_top.cov_ndf),17);
    bufp->fullCData(oldp+95,(vlSymsp->TOP__spi_xfer_top.cov_tmod),2);
    bufp->fullCData(oldp+96,(vlSymsp->TOP__spi_xfer_top.cov_frf),2);
    bufp->fullBit(oldp+97,(vlSymsp->TOP__spi_xfer_top.cov_scph));
    bufp->fullBit(oldp+98,(vlSymsp->TOP__spi_xfer_top.cov_scpol));
    bufp->fullBit(oldp+99,(vlSymsp->TOP__spi_xfer_top.cov_srl_test));
    bufp->fullBit(oldp+100,(vlSymsp->TOP__spi_xfer_top.cov_ss_tgl_en));
    bufp->fullCData(oldp+101,(vlSymsp->TOP__spi_xfer_top.cov_ser),4);
    bufp->fullCData(oldp+102,(vlSymsp->TOP__spi_xfer_top.cov_tx_level),4);
    bufp->fullCData(oldp+103,(vlSymsp->TOP__spi_xfer_top.cov_rx_level),4);
    bufp->fullBit(oldp+104,(vlSymsp->TOP__spi_xfer_top.cov_tx_empty));
    bufp->fullBit(oldp+105,(vlSymsp->TOP__spi_xfer_top.cov_tx_full));
    bufp->fullBit(oldp+106,(vlSymsp->TOP__spi_xfer_top.cov_rx_empty));
    bufp->fullBit(oldp+107,(vlSymsp->TOP__spi_xfer_top.cov_rx_full));
    bufp->fullCData(oldp+108,(vlSymsp->TOP__spi_xfer_top.cov_hold_ss_cnt),4);
    bufp->fullBit(oldp+109,(vlSymsp->TOP__spi_xfer_top.cov_s0));
    bufp->fullBit(oldp+110,(vlSymsp->TOP__spi_xfer_top.cov_s1));
    bufp->fullBit(oldp+111,(vlSymsp->TOP__spi_xfer_top.cov_s2));
    bufp->fullIData(oldp+112,(vlSymsp->TOP__spi_xfer_top.cov_rx_data),32);
    bufp->fullBit(oldp+113,(vlSymsp->TOP__spi_xfer_top.cov_ss_in_n));
    bufp->fullBit(oldp+114,(vlSymsp->TOP__spi_xfer_top.cov_start_xfer));
    bufp->fullBit(oldp+115,(vlSymsp->TOP__spi_xfer_top.sclk_re));
    bufp->fullBit(oldp+116,(vlSymsp->TOP__spi_xfer_top.sclk_fe));
    bufp->fullBit(oldp+117,(vlSymsp->TOP__spi_xfer_top.sclk_mask));
    bufp->fullBit(oldp+118,(vlSymsp->TOP__spi_xfer_top.fsm_slv_sel));
    bufp->fullBit(oldp+119,(vlSymsp->TOP__spi_xfer_top.load_tx_shift));
    bufp->fullBit(oldp+120,(vlSymsp->TOP__spi_xfer_top.load_tx_buffer));
    bufp->fullBit(oldp+121,(vlSymsp->TOP__spi_xfer_top.load_rx_buf));
    bufp->fullBit(oldp+122,(vlSymsp->TOP__spi_xfer_top.tx_shift_en));
    bufp->fullBit(oldp+123,(vlSymsp->TOP__spi_xfer_top.rx_shift_en));
    bufp->fullCData(oldp+124,(vlSymsp->TOP__spi_xfer_top.tx_dfs),6);
    bufp->fullBit(oldp+125,(vlSymsp->TOP__spi_xfer_top.ssi_oe_n));
    bufp->fullBit(oldp+126,(vlSymsp->TOP__spi_xfer_top.fsm_busy));
    bufp->fullBit(oldp+127,(vlSymsp->TOP__spi_xfer_top.fsm_sleep));
    bufp->fullBit(oldp+128,(vlSymsp->TOP__spi_xfer_top.tx_pop));
    bufp->fullBit(oldp+129,(vlSymsp->TOP__spi_xfer_top.rx_push));
    bufp->fullBit(oldp+130,(vlSymsp->TOP__spi_xfer_top.tx_push));
    bufp->fullBit(oldp+131,(vlSymsp->TOP__spi_xfer_top.rx_pop));
    bufp->fullBit(oldp+132,(vlSymsp->TOP__spi_xfer_top.tx_full));
    bufp->fullBit(oldp+133,(vlSymsp->TOP__spi_xfer_top.tx_empty));
    bufp->fullBit(oldp+134,(vlSymsp->TOP__spi_xfer_top.rx_full));
    bufp->fullBit(oldp+135,(vlSymsp->TOP__spi_xfer_top.rx_empty));
    bufp->fullCData(oldp+136,(vlSymsp->TOP__spi_xfer_top.tx_level),4);
    bufp->fullCData(oldp+137,(vlSymsp->TOP__spi_xfer_top.rx_level),4);
    bufp->fullIData(oldp+138,(vlSymsp->TOP__spi_xfer_top.tx_pop_data),32);
    bufp->fullIData(oldp+139,(vlSymsp->TOP__spi_xfer_top.rx_pop_data),32);
    bufp->fullIData(oldp+140,(vlSymsp->TOP__spi_xfer_top.rx_push_data),32);
    bufp->fullCData(oldp+141,(vlSymsp->TOP__spi_xfer_top.fsm_c_state),4);
    bufp->fullBit(oldp+142,(vlSymsp->TOP__spi_xfer_top.start_xfer));
    bufp->fullBit(oldp+143,(vlSymsp->TOP__spi_xfer_top.baud2));
    bufp->fullIData(oldp+144,(vlSymsp->TOP__spi_xfer_top.ctrlr0),32);
    bufp->fullIData(oldp+145,(vlSymsp->TOP__spi_xfer_top.ctrlr1),32);
    bufp->fullBit(oldp+146,(vlSymsp->TOP__spi_xfer_top.ssienr));
    bufp->fullCData(oldp+147,(vlSymsp->TOP__spi_xfer_top.ser),4);
    bufp->fullSData(oldp+148,(vlSymsp->TOP__spi_xfer_top.baudr),16);
    bufp->fullCData(oldp+149,(vlSymsp->TOP__spi_xfer_top.txftlr),4);
    bufp->fullCData(oldp+150,(vlSymsp->TOP__spi_xfer_top.dfs),5);
    bufp->fullCData(oldp+151,(vlSymsp->TOP__spi_xfer_top.frf),2);
    bufp->fullBit(oldp+152,(vlSymsp->TOP__spi_xfer_top.scph));
    bufp->fullBit(oldp+153,(vlSymsp->TOP__spi_xfer_top.scpol));
    bufp->fullCData(oldp+154,(vlSymsp->TOP__spi_xfer_top.tmod),2);
    bufp->fullBit(oldp+155,(vlSymsp->TOP__spi_xfer_top.srl_test));
    bufp->fullBit(oldp+156,(vlSymsp->TOP__spi_xfer_top.ss_tgl_en));
    bufp->fullIData(oldp+157,(vlSymsp->TOP__spi_xfer_top.ndf),17);
    bufp->fullCData(oldp+158,(vlSymsp->TOP__spi_xfer_top.dfs_dec),6);
    bufp->fullCData(oldp+159,(vlSymsp->TOP__spi_xfer_top.dfs_eff),6);
    bufp->fullCData(oldp+160,(vlSymsp->TOP__spi_xfer_top.prev_fsm_state),4);
    bufp->fullBit(oldp+161,(vlSymsp->TOP__spi_xfer_top.write_active_r));
    bufp->fullBit(oldp+162,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__clk));
    bufp->fullBit(oldp+163,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rst_n));
    bufp->fullBit(oldp+164,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_push));
    bufp->fullIData(oldp+165,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_push_data),32);
    bufp->fullBit(oldp+166,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_pop));
    bufp->fullBit(oldp+167,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_push));
    bufp->fullIData(oldp+168,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_push_data),32);
    bufp->fullBit(oldp+169,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_pop));
    bufp->fullBit(oldp+170,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_full));
    bufp->fullBit(oldp+171,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_empty));
    bufp->fullBit(oldp+172,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_full));
    bufp->fullBit(oldp+173,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_empty));
    bufp->fullCData(oldp+174,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_level),4);
    bufp->fullCData(oldp+175,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_level),4);
    bufp->fullIData(oldp+176,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_pop_data),32);
    bufp->fullIData(oldp+177,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_pop_data),32);
    bufp->fullIData(oldp+178,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_mem[0]),32);
    bufp->fullIData(oldp+179,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_mem[1]),32);
    bufp->fullIData(oldp+180,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_mem[2]),32);
    bufp->fullIData(oldp+181,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_mem[3]),32);
    bufp->fullIData(oldp+182,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_mem[4]),32);
    bufp->fullIData(oldp+183,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_mem[5]),32);
    bufp->fullIData(oldp+184,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_mem[6]),32);
    bufp->fullIData(oldp+185,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_mem[7]),32);
    bufp->fullIData(oldp+186,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_mem[0]),32);
    bufp->fullIData(oldp+187,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_mem[1]),32);
    bufp->fullIData(oldp+188,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_mem[2]),32);
    bufp->fullIData(oldp+189,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_mem[3]),32);
    bufp->fullIData(oldp+190,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_mem[4]),32);
    bufp->fullIData(oldp+191,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_mem[5]),32);
    bufp->fullIData(oldp+192,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_mem[6]),32);
    bufp->fullIData(oldp+193,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_mem[7]),32);
    bufp->fullCData(oldp+194,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_wr_ptr),3);
    bufp->fullCData(oldp+195,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_rd_ptr),3);
    bufp->fullCData(oldp+196,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_wr_ptr),3);
    bufp->fullCData(oldp+197,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_rd_ptr),3);
    bufp->fullCData(oldp+198,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_cnt),4);
    bufp->fullCData(oldp+199,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_cnt),4);
    bufp->fullBit(oldp+200,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_wr_ok));
    bufp->fullBit(oldp+201,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__tx_rd_ok));
    bufp->fullBit(oldp+202,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_wr_ok));
    bufp->fullBit(oldp+203,(vlSymsp->TOP__spi_xfer_top.u_fifo__DOT__rx_rd_ok));
    bufp->fullBit(oldp+204,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__clk));
    bufp->fullBit(oldp+205,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__rst_n));
    bufp->fullBit(oldp+206,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__ssi_en));
    bufp->fullBit(oldp+207,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__start_xfer));
    bufp->fullBit(oldp+208,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__tx_empty));
    bufp->fullCData(oldp+209,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__tx_fifo_level),4);
    bufp->fullCData(oldp+210,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__txfthr),4);
    bufp->fullBit(oldp+211,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__sclk_re));
    bufp->fullBit(oldp+212,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__sclk_fe));
    bufp->fullCData(oldp+213,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__frf),2);
    bufp->fullBit(oldp+214,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__scph));
    bufp->fullCData(oldp+215,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__tmod),2);
    bufp->fullCData(oldp+216,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__dfs),6);
    bufp->fullIData(oldp+217,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__ndf),17);
    bufp->fullBit(oldp+218,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__ss_tgl_en));
    bufp->fullBit(oldp+219,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__ss_in_n));
    bufp->fullBit(oldp+220,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__baud2));
    bufp->fullCData(oldp+221,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__spec_hold_ss),4);
    bufp->fullCData(oldp+222,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__c_state),4);
    bufp->fullBit(oldp+223,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__fsm_busy));
    bufp->fullBit(oldp+224,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__fsm_sleep));
    bufp->fullBit(oldp+225,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__sclk_mask));
    bufp->fullBit(oldp+226,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__fsm_slv_sel));
    bufp->fullBit(oldp+227,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__load_tx_shift));
    bufp->fullBit(oldp+228,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__load_tx_buffer));
    bufp->fullBit(oldp+229,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__load_rx_buf));
    bufp->fullBit(oldp+230,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__tx_shift_en));
    bufp->fullBit(oldp+231,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__rx_shift_en));
    bufp->fullCData(oldp+232,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__tx_dfs),6);
    bufp->fullBit(oldp+233,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__ssi_oe_n));
    bufp->fullSData(oldp+234,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__cov_fsm_state),11);
    bufp->fullCData(oldp+235,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__cov_bit_cnt),6);
    bufp->fullIData(oldp+236,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__cov_frame_cnt),17);
    bufp->fullBit(oldp+237,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__cov_x_done));
    bufp->fullBit(oldp+238,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__cov_last_frame));
    bufp->fullBit(oldp+239,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__cov_tx_shift_en));
    bufp->fullBit(oldp+240,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__cov_rx_shift_en));
    bufp->fullBit(oldp+241,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__cov_load_tx_shift));
    bufp->fullBit(oldp+242,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__cov_load_rx_buf));
    bufp->fullCData(oldp+243,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__cov_hold_ss_cnt),4);
    bufp->fullBit(oldp+244,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__cov_s0));
    bufp->fullBit(oldp+245,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__cov_s1));
    bufp->fullBit(oldp+246,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__spi0));
    bufp->fullBit(oldp+247,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__spi1));
    bufp->fullBit(oldp+248,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__ssp));
    bufp->fullBit(oldp+249,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__sclk_re_int));
    bufp->fullBit(oldp+250,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__sclk_fe_int));
    bufp->fullCData(oldp+251,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__bit_cnt),6);
    bufp->fullIData(oldp+252,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__frame_cnt),17);
    bufp->fullBit(oldp+253,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__last_frame));
    bufp->fullBit(oldp+254,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__x_done_1d));
    bufp->fullBit(oldp+255,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__tx_load_en));
    bufp->fullBit(oldp+256,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__abort_ir));
    bufp->fullCData(oldp+257,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__hold_cnt),4);
    bufp->fullCData(oldp+258,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__n_state),4);
    bufp->fullCData(oldp+259,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__dfs_eff),6);
    bufp->fullBit(oldp+260,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__f_done));
    bufp->fullBit(oldp+261,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__sspf_done));
    bufp->fullBit(oldp+262,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__tx_fifo_filled));
    bufp->fullBit(oldp+263,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__x_done));
    bufp->fullBit(oldp+264,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__inc_bit_cnt));
    bufp->fullBit(oldp+265,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__clr_bit_cnt));
    bufp->fullBit(oldp+266,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__inc_frame_cnt));
    bufp->fullBit(oldp+267,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__clr_frame_cnt));
    bufp->fullBit(oldp+268,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__abort_now));
    bufp->fullBit(oldp+269,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__busy_now));
    bufp->fullBit(oldp+270,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__refill_now));
    bufp->fullBit(oldp+271,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__abort_seen_r));
    bufp->fullBit(oldp+272,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__refill_seen_r));
    bufp->fullBit(oldp+273,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__fsm_sleep_ir));
    bufp->fullBit(oldp+274,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__fsm_busy_ir));
    bufp->fullBit(oldp+275,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__rx_load_gate));
    bufp->fullBit(oldp+276,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__ssi_oe_n_iw));
    bufp->fullBit(oldp+277,(vlSymsp->TOP__spi_xfer_top.u_mstfsm__DOT__ssi_oe_n_ir));
    bufp->fullBit(oldp+278,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__clk));
    bufp->fullBit(oldp+279,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__rst_n));
    bufp->fullBit(oldp+280,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__reg_we));
    bufp->fullCData(oldp+281,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__reg_addr),4);
    bufp->fullIData(oldp+282,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__reg_wdata),32);
    bufp->fullBit(oldp+283,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__reg_re));
    bufp->fullIData(oldp+284,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__reg_rdata),32);
    bufp->fullIData(oldp+285,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__ctrlr0),32);
    bufp->fullIData(oldp+286,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__ctrlr1),32);
    bufp->fullBit(oldp+287,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__ssienr));
    bufp->fullCData(oldp+288,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__ser),4);
    bufp->fullSData(oldp+289,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__baudr),16);
    bufp->fullCData(oldp+290,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__txftlr),4);
    bufp->fullBit(oldp+291,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__fsm_busy));
    bufp->fullBit(oldp+292,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__tx_full));
    bufp->fullBit(oldp+293,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__tx_empty));
    bufp->fullCData(oldp+294,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__tx_level),4);
    bufp->fullBit(oldp+295,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__rx_full));
    bufp->fullBit(oldp+296,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__rx_empty));
    bufp->fullCData(oldp+297,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__rx_level),4);
    bufp->fullIData(oldp+298,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__rx_pop_data),32);
    bufp->fullBit(oldp+299,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__tx_pop));
    bufp->fullBit(oldp+300,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__tx_push));
    bufp->fullBit(oldp+301,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__rx_pop));
    bufp->fullBit(oldp+302,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__start_xfer));
    bufp->fullBit(oldp+303,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__slv_sel));
    bufp->fullBit(oldp+304,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__tx_empty_early));
    bufp->fullBit(oldp+305,(vlSymsp->TOP__spi_xfer_top.u_regfile__DOT__tx_fifo_ready));
    bufp->fullBit(oldp+306,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__clk));
    bufp->fullBit(oldp+307,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__rst_n));
    bufp->fullBit(oldp+308,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__ssi_en));
    bufp->fullSData(oldp+309,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__baudr),16);
    bufp->fullBit(oldp+310,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__sclk_mask));
    bufp->fullBit(oldp+311,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__sclk_active));
    bufp->fullBit(oldp+312,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__sclk_out));
    bufp->fullBit(oldp+313,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__sclk_re));
    bufp->fullBit(oldp+314,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__sclk_fe));
    bufp->fullSData(oldp+315,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__ssi_cnt_out),16);
    bufp->fullSData(oldp+316,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__ssi_cnt),16);
    bufp->fullBit(oldp+317,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__sclk_re_ir));
    bufp->fullBit(oldp+318,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__sclk_fe_ir));
    bufp->fullSData(oldp+319,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__r_det),16);
    bufp->fullSData(oldp+320,(vlSymsp->TOP__spi_xfer_top.u_sclkgen__DOT__f_det),16);
    bufp->fullBit(oldp+321,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__clk));
    bufp->fullBit(oldp+322,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__rst_n));
    bufp->fullBit(oldp+323,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__tx_shift_en));
    bufp->fullBit(oldp+324,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__load_tx_shift));
    bufp->fullBit(oldp+325,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__load_tx_buffer));
    bufp->fullBit(oldp+326,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__rx_shift_en));
    bufp->fullBit(oldp+327,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__load_rx_buf));
    bufp->fullIData(oldp+328,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__tx_pop_data),32);
    bufp->fullBit(oldp+329,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__rxd));
    bufp->fullCData(oldp+330,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__dfs),6);
    bufp->fullBit(oldp+331,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__fsm_slv_sel));
    bufp->fullCData(oldp+332,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__ser),4);
    bufp->fullCData(oldp+333,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__frf),2);
    bufp->fullBit(oldp+334,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__srl_test));
    bufp->fullBit(oldp+335,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__ssi_en));
    bufp->fullBit(oldp+336,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__txd));
    bufp->fullBit(oldp+337,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__tx_pop));
    bufp->fullBit(oldp+338,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__rx_push));
    bufp->fullCData(oldp+339,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__ss_n),4);
    bufp->fullIData(oldp+340,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__rx_push_data),32);
    bufp->fullBit(oldp+341,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__cov_txd));
    bufp->fullIData(oldp+342,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__cov_rx_buffer),32);
    bufp->fullIData(oldp+343,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__tx_shift_reg),32);
    bufp->fullIData(oldp+344,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__tx_buffer),32);
    bufp->fullIData(oldp+345,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__rx_shift_reg),32);
    bufp->fullIData(oldp+346,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__rx_buffer),32);
    bufp->fullBit(oldp+347,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__tx_pop_ir));
    bufp->fullBit(oldp+348,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__rx_push_ir));
    bufp->fullBit(oldp+349,(vlSymsp->TOP__spi_xfer_top.u_shift__DOT__rxd_mst_int));
}
